#ifndef _R_EX_R_H_
#define _R_EX_R_H_
/*
** File: C:\Documents and Settings\emeliehe\Desktop\ESlab7\Embedded7\r_ex_r.h
** Generated by XMLLauncher v3.9.1.77 x86 2011a
**
** Copyright 1995-2011 Arcticus Systems AB, All rights reserved.
** The format and content in the File is protected by copyright.
** The File is furnished under a licence and may only be used in
** accordance with the terms of this licence.
** Rubus® is a registered trademark to which Arcticus has all exclusive rights.
*/

/*==========================================================
** Include files
==========================================================*/
#include <basic/bs_basic.h>
#include <red/r_thread.h>

/*==========================================================
** Inline
==========================================================*/
#include "red.h"
#ifdef __cplusplus
extern "C" {
#endif

/*==========================================================
** Red Thread redStart
==========================================================*/
extern redThreadAttr_t const redStart;
extern void redStartMain(void);

/*==========================================================
** Red Thread blinkyResched
==========================================================*/
extern redThreadAttr_t const blinkyResched;
extern blinkyModeType blinkyReschedArgs;
extern void blinkyReschedMain(blinkyModeType *args);

/*==========================================================
** Red Thread blinky0
==========================================================*/
extern redThreadAttr_t const blinky0;
extern int blinky0Args;
extern void blinky0Main(int *args);

/*==========================================================
** Red Thread blinky1
==========================================================*/
extern redThreadAttr_t const blinky1;
extern int blinky1Args;
extern void blinky1Main(int *args);

/*==========================================================
** Red Thread blinky2
==========================================================*/
extern redThreadAttr_t const blinky2;
extern int blinky2Args;
extern void blinky2Main(int *args);

/*==========================================================
** Red Thread blinky3
==========================================================*/
extern redThreadAttr_t const blinky3;
extern int blinky3Args;
extern void blinky3Main(int *args);

/*==========================================================
** Red Schedule redScheduleBlinky0
==========================================================*/
extern redSchedAttr_t const redScheduleBlinky0;

/*==========================================================
** Red Schedule redSchedule2
==========================================================*/
extern redSchedAttr_t const redSchedule2;

/*==========================================================
** Red Schedule redScheduleStart
==========================================================*/
extern redSchedAttr_t const redScheduleStart;


#ifdef __cplusplus
}
#endif


#endif
