#ifndef _R_EX_G_H_
#define _R_EX_G_H_
/*
** File: C:\Documents and Settings\emeliehe\Desktop\ESlab7\Embedded7\r_ex_g.h
** Generated by XMLLauncher v3.9.1.77 x86 2011a
**
** Copyright 1995-2011 Arcticus Systems AB, All rights reserved.
** The format and content in the File is protected by copyright.
** The File is furnished under a licence and may only be used in
** accordance with the terms of this licence.
** Rubus® is a registered trademark to which Arcticus has all exclusive rights.
*/

/*==========================================================
** Include files
==========================================================*/
#include <basic/bs_basic.h>
#include <green/g_thread.h>
#include <blue/b_signal.h>

/*==========================================================
** Inline
==========================================================*/
#include "red.h"
#ifdef __cplusplus
extern "C" {
#endif

/*==========================================================
** Green Thread comXhpRx
==========================================================*/
extern greenThreadAttr_t const comXhpRx;
extern void comXhpRx_entry(void);

/*==========================================================
** Green Thread comXhpTx
==========================================================*/
extern greenThreadAttr_t const comXhpTx;
extern void comXhpTx_entry(void);


#ifdef __cplusplus
}
#endif


#endif
