#ifndef _R_EX_BS_H_
#define _R_EX_BS_H_
/*
** File: C:\Documents and Settings\emeliehe\Desktop\Embedded7\r_ex_bs.h
** Generated by XMLLauncher v3.9.1.77 x86 2011a
**
** Copyright 1995-2011 Arcticus Systems AB, All rights reserved.
** The format and content in the File is protected by copyright.
** The File is furnished under a licence and may only be used in
** accordance with the terms of this licence.
** Rubus® is a registered trademark to which Arcticus has all exclusive rights.
*/

/*==========================================================
** Include files
==========================================================*/
#include <basic/bs_basic.h>
#include <rubusOS_cfg.h>

#ifdef __cplusplus
extern "C" {
#endif


extern bsIdNameElement_t const bsIdNameTable[15];
extern bsName_t bsObjectName(int_t id);
extern int_t bsObjectByName(bsName_t str);


#ifdef __cplusplus
}
#endif


#endif
