/*
** File: C:\Documents and Settings\emeliehe\Desktop\ESlab7\Embedded7\r_ex_c.c
** Generated by XMLLauncher v3.9.1.77 x86 2011a
**
** Copyright 1995-2011 Arcticus Systems AB, All rights reserved.
** The format and content in the File is protected by copyright.
** The File is furnished under a licence and may only be used in
** accordance with the terms of this licence.
** Rubus® is a registered trademark to which Arcticus has all exclusive rights.
*/

/*==========================================================
** Include files
==========================================================*/
#include <basic/bs_basic.h>
#include <basic/bs_log.h>
#include <hal/hal_cfg.h>
#include <rubusOS_cfg.h>
#include "r_ex_bs.h"
#include "r_ex_r.h"
#include "r_ex_g.h"
#include "r_ex_b.h"

/*==========================================================
** Green Thread comXhpRx
==========================================================*/
extern greenThreadCB_t comXhpRxCB;
void comXhpRxInternal(void)

{ R_TYPE_TIME_EXEC execTime;

  greenEnter();
  bsLogPut(3,R_LOG_EVENT_1);
  R_EXEC_TIME_START(execTime)
  comXhpRx_entry();
  R_EXEC_TIME_STOP(execTime,execTime,0u)
  bsLogPut(3,R_LOG_EVENT_2);
  greenExit();
}

/*==========================================================
** Green Thread comXhpTx
==========================================================*/
extern greenThreadCB_t comXhpTxCB;
void comXhpTxInternal(void)

{ R_TYPE_TIME_EXEC execTime;

  greenEnter();
  bsLogPut(4,R_LOG_EVENT_1);
  R_EXEC_TIME_START(execTime)
  comXhpTx_entry();
  R_EXEC_TIME_STOP(execTime,execTime,0u)
  bsLogPut(4,R_LOG_EVENT_2);
  greenExit();
}

/*==========================================================
** redStartInternal()
==========================================================*/
extern redThreadCB_t redStartCB;
void redStartInternal(int_t deadline)

{ R_TYPE_TIME_EXEC execTime;

  bsLogPut(11,R_LOG_EVENT_1);
  R_RED_SET_DEADLINE(&redStart,deadline)
  R_EXEC_TIME_START(execTime)
  R_RED_KERNEL_EXIT;
  redStartMain();
  R_RED_KERNEL_ENTER;
  R_EXEC_TIME_STOP(execTime,execTime,0u)
  bsLogPut(11,R_LOG_EVENT_2);
}

/*==========================================================
** blinkyReschedInternal()
==========================================================*/
extern redThreadCB_t blinkyReschedCB;
void blinkyReschedInternal(int_t deadline)

{ R_TYPE_TIME_EXEC execTime;

  bsLogPut(12,R_LOG_EVENT_1);
  R_RED_SET_DEADLINE(&blinkyResched,deadline)
  R_EXEC_TIME_START(execTime)
  R_RED_KERNEL_EXIT;
  blinkyReschedMain(&blinkyReschedArgs);
  R_RED_KERNEL_ENTER;
  R_EXEC_TIME_STOP(execTime,execTime,0u)
  bsLogPut(12,R_LOG_EVENT_2);
}

/*==========================================================
** blinky0Internal()
==========================================================*/
extern redThreadCB_t blinky0CB;
void blinky0Internal(int_t deadline)

{ R_TYPE_TIME_EXEC execTime;

  bsLogPut(13,R_LOG_EVENT_1);
  R_RED_SET_DEADLINE(&blinky0,deadline)
  R_EXEC_TIME_START(execTime)
  R_RED_KERNEL_EXIT;
  blinky0Main(&blinky0Args);
  R_RED_KERNEL_ENTER;
  R_EXEC_TIME_STOP(execTime,execTime,0u)
  bsLogPut(13,R_LOG_EVENT_2);
}

/*==========================================================
** blinky1Internal()
==========================================================*/
extern redThreadCB_t blinky1CB;
void blinky1Internal(int_t deadline)

{ R_TYPE_TIME_EXEC execTime;

  bsLogPut(14,R_LOG_EVENT_1);
  R_RED_SET_DEADLINE(&blinky1,deadline)
  R_EXEC_TIME_START(execTime)
  R_RED_KERNEL_EXIT;
  blinky1Main(&blinky1Args);
  R_RED_KERNEL_ENTER;
  R_EXEC_TIME_STOP(execTime,execTime,0u)
  bsLogPut(14,R_LOG_EVENT_2);
}

/*==========================================================
** blinky2Internal()
==========================================================*/
extern redThreadCB_t blinky2CB;
void blinky2Internal(int_t deadline)

{ R_TYPE_TIME_EXEC execTime;

  bsLogPut(15,R_LOG_EVENT_1);
  R_RED_SET_DEADLINE(&blinky2,deadline)
  R_EXEC_TIME_START(execTime)
  R_RED_KERNEL_EXIT;
  blinky2Main(&blinky2Args);
  R_RED_KERNEL_ENTER;
  R_EXEC_TIME_STOP(execTime,execTime,0u)
  bsLogPut(15,R_LOG_EVENT_2);
}

/*==========================================================
** blinky3Internal()
==========================================================*/
extern redThreadCB_t blinky3CB;
void blinky3Internal(int_t deadline)

{ R_TYPE_TIME_EXEC execTime;

  bsLogPut(16,R_LOG_EVENT_1);
  R_RED_SET_DEADLINE(&blinky3,deadline)
  R_EXEC_TIME_START(execTime)
  R_RED_KERNEL_EXIT;
  blinky3Main(&blinky3Args);
  R_RED_KERNEL_ENTER;
  R_EXEC_TIME_STOP(execTime,execTime,0u)
  bsLogPut(16,R_LOG_EVENT_2);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 0
==========================================================*/
extern void redScheduleBlinky0_5(void);
void redScheduleBlinky0_0(void)

{
  bsLogPut(17,R_LOG_EVENT_1);
  R_RED_NEXT(&redScheduleBlinky0_5,5)
  blueActivate(&blueKernel);
  blinky0Internal(2);
  blinkyReschedInternal(99);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 5
==========================================================*/
extern void redScheduleBlinky0_10(void);
void redScheduleBlinky0_5(void)

{
  R_RED_NEXT(&redScheduleBlinky0_10,10)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 10
==========================================================*/
extern void redScheduleBlinky0_15(void);
void redScheduleBlinky0_10(void)

{
  R_RED_NEXT(&redScheduleBlinky0_15,15)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 15
==========================================================*/
extern void redScheduleBlinky0_20(void);
void redScheduleBlinky0_15(void)

{
  R_RED_NEXT(&redScheduleBlinky0_20,20)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 20
==========================================================*/
extern void redScheduleBlinky0_25(void);
void redScheduleBlinky0_20(void)

{
  R_RED_NEXT(&redScheduleBlinky0_25,25)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 25
==========================================================*/
extern void redScheduleBlinky0_30(void);
void redScheduleBlinky0_25(void)

{
  R_RED_NEXT(&redScheduleBlinky0_30,30)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 30
==========================================================*/
extern void redScheduleBlinky0_35(void);
void redScheduleBlinky0_30(void)

{
  R_RED_NEXT(&redScheduleBlinky0_35,35)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 35
==========================================================*/
extern void redScheduleBlinky0_40(void);
void redScheduleBlinky0_35(void)

{
  R_RED_NEXT(&redScheduleBlinky0_40,40)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 40
==========================================================*/
extern void redScheduleBlinky0_45(void);
void redScheduleBlinky0_40(void)

{
  R_RED_NEXT(&redScheduleBlinky0_45,45)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 45
==========================================================*/
extern void redScheduleBlinky0_50(void);
void redScheduleBlinky0_45(void)

{
  R_RED_NEXT(&redScheduleBlinky0_50,50)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 50
==========================================================*/
extern void redScheduleBlinky0_55(void);
void redScheduleBlinky0_50(void)

{
  R_RED_NEXT(&redScheduleBlinky0_55,55)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 55
==========================================================*/
extern void redScheduleBlinky0_60(void);
void redScheduleBlinky0_55(void)

{
  R_RED_NEXT(&redScheduleBlinky0_60,60)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 60
==========================================================*/
extern void redScheduleBlinky0_65(void);
void redScheduleBlinky0_60(void)

{
  R_RED_NEXT(&redScheduleBlinky0_65,65)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 65
==========================================================*/
extern void redScheduleBlinky0_70(void);
void redScheduleBlinky0_65(void)

{
  R_RED_NEXT(&redScheduleBlinky0_70,70)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 70
==========================================================*/
extern void redScheduleBlinky0_75(void);
void redScheduleBlinky0_70(void)

{
  R_RED_NEXT(&redScheduleBlinky0_75,75)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 75
==========================================================*/
extern void redScheduleBlinky0_80(void);
void redScheduleBlinky0_75(void)

{
  R_RED_NEXT(&redScheduleBlinky0_80,80)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 80
==========================================================*/
extern void redScheduleBlinky0_85(void);
void redScheduleBlinky0_80(void)

{
  R_RED_NEXT(&redScheduleBlinky0_85,85)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 85
==========================================================*/
extern void redScheduleBlinky0_90(void);
void redScheduleBlinky0_85(void)

{
  R_RED_NEXT(&redScheduleBlinky0_90,90)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 90
==========================================================*/
extern void redScheduleBlinky0_95(void);
void redScheduleBlinky0_90(void)

{
  R_RED_NEXT(&redScheduleBlinky0_95,95)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleBlinky0 Releasetime 95
==========================================================*/
extern void redScheduleBlinky0_0(void);
void redScheduleBlinky0_95(void)

{
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 0
==========================================================*/
extern void redSchedule2_5(void);
void redSchedule2_0(void)

{
  bsLogPut(18,R_LOG_EVENT_1);
  R_RED_NEXT(&redSchedule2_5,5)
  blueActivate(&blueKernel);
  blinky0Internal(2);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 5
==========================================================*/
extern void redSchedule2_10(void);
void redSchedule2_5(void)

{
  R_RED_NEXT(&redSchedule2_10,10)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 10
==========================================================*/
extern void redSchedule2_15(void);
void redSchedule2_10(void)

{
  R_RED_NEXT(&redSchedule2_15,15)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 15
==========================================================*/
extern void redSchedule2_20(void);
void redSchedule2_15(void)

{
  R_RED_NEXT(&redSchedule2_20,20)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 20
==========================================================*/
extern void redSchedule2_25(void);
void redSchedule2_20(void)

{
  R_RED_NEXT(&redSchedule2_25,25)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 25
==========================================================*/
extern void redSchedule2_30(void);
void redSchedule2_25(void)

{
  R_RED_NEXT(&redSchedule2_30,30)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 30
==========================================================*/
extern void redSchedule2_35(void);
void redSchedule2_30(void)

{
  R_RED_NEXT(&redSchedule2_35,35)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 35
==========================================================*/
extern void redSchedule2_40(void);
void redSchedule2_35(void)

{
  R_RED_NEXT(&redSchedule2_40,40)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 40
==========================================================*/
extern void redSchedule2_45(void);
void redSchedule2_40(void)

{
  R_RED_NEXT(&redSchedule2_45,45)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 45
==========================================================*/
extern void redSchedule2_50(void);
void redSchedule2_45(void)

{
  R_RED_NEXT(&redSchedule2_50,50)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 50
==========================================================*/
extern void redSchedule2_55(void);
void redSchedule2_50(void)

{
  R_RED_NEXT(&redSchedule2_55,55)
  blueActivate(&blueKernel);
  blinky1Internal(52);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 55
==========================================================*/
extern void redSchedule2_60(void);
void redSchedule2_55(void)

{
  R_RED_NEXT(&redSchedule2_60,60)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 60
==========================================================*/
extern void redSchedule2_65(void);
void redSchedule2_60(void)

{
  R_RED_NEXT(&redSchedule2_65,65)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 65
==========================================================*/
extern void redSchedule2_70(void);
void redSchedule2_65(void)

{
  R_RED_NEXT(&redSchedule2_70,70)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 70
==========================================================*/
extern void redSchedule2_75(void);
void redSchedule2_70(void)

{
  R_RED_NEXT(&redSchedule2_75,75)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 75
==========================================================*/
extern void redSchedule2_80(void);
void redSchedule2_75(void)

{
  R_RED_NEXT(&redSchedule2_80,80)
  blueActivate(&blueKernel);
  blinky2Internal(102);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 80
==========================================================*/
extern void redSchedule2_85(void);
void redSchedule2_80(void)

{
  R_RED_NEXT(&redSchedule2_85,85)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 85
==========================================================*/
extern void redSchedule2_90(void);
void redSchedule2_85(void)

{
  R_RED_NEXT(&redSchedule2_90,90)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 90
==========================================================*/
extern void redSchedule2_95(void);
void redSchedule2_90(void)

{
  R_RED_NEXT(&redSchedule2_95,95)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 95
==========================================================*/
extern void redSchedule2_100(void);
void redSchedule2_95(void)

{
  R_RED_NEXT(&redSchedule2_100,100)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 100
==========================================================*/
extern void redSchedule2_105(void);
void redSchedule2_100(void)

{
  R_RED_NEXT(&redSchedule2_105,105)
  blueActivate(&blueKernel);
  blinky3Internal(152);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 105
==========================================================*/
extern void redSchedule2_110(void);
void redSchedule2_105(void)

{
  R_RED_NEXT(&redSchedule2_110,110)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 110
==========================================================*/
extern void redSchedule2_115(void);
void redSchedule2_110(void)

{
  R_RED_NEXT(&redSchedule2_115,115)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 115
==========================================================*/
extern void redSchedule2_120(void);
void redSchedule2_115(void)

{
  R_RED_NEXT(&redSchedule2_120,120)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 120
==========================================================*/
extern void redSchedule2_125(void);
void redSchedule2_120(void)

{
  R_RED_NEXT(&redSchedule2_125,125)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 125
==========================================================*/
extern void redSchedule2_130(void);
void redSchedule2_125(void)

{
  R_RED_NEXT(&redSchedule2_130,130)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 130
==========================================================*/
extern void redSchedule2_135(void);
void redSchedule2_130(void)

{
  R_RED_NEXT(&redSchedule2_135,135)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 135
==========================================================*/
extern void redSchedule2_140(void);
void redSchedule2_135(void)

{
  R_RED_NEXT(&redSchedule2_140,140)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 140
==========================================================*/
extern void redSchedule2_145(void);
void redSchedule2_140(void)

{
  R_RED_NEXT(&redSchedule2_145,145)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 145
==========================================================*/
extern void redSchedule2_150(void);
void redSchedule2_145(void)

{
  R_RED_NEXT(&redSchedule2_150,150)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 150
==========================================================*/
extern void redSchedule2_155(void);
void redSchedule2_150(void)

{
  R_RED_NEXT(&redSchedule2_155,155)
  blueActivate(&blueKernel);
  blinkyReschedInternal(199);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 155
==========================================================*/
extern void redSchedule2_160(void);
void redSchedule2_155(void)

{
  R_RED_NEXT(&redSchedule2_160,160)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 160
==========================================================*/
extern void redSchedule2_165(void);
void redSchedule2_160(void)

{
  R_RED_NEXT(&redSchedule2_165,165)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 165
==========================================================*/
extern void redSchedule2_170(void);
void redSchedule2_165(void)

{
  R_RED_NEXT(&redSchedule2_170,170)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 170
==========================================================*/
extern void redSchedule2_175(void);
void redSchedule2_170(void)

{
  R_RED_NEXT(&redSchedule2_175,175)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 175
==========================================================*/
extern void redSchedule2_180(void);
void redSchedule2_175(void)

{
  R_RED_NEXT(&redSchedule2_180,180)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 180
==========================================================*/
extern void redSchedule2_185(void);
void redSchedule2_180(void)

{
  R_RED_NEXT(&redSchedule2_185,185)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 185
==========================================================*/
extern void redSchedule2_190(void);
void redSchedule2_185(void)

{
  R_RED_NEXT(&redSchedule2_190,190)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 190
==========================================================*/
extern void redSchedule2_195(void);
void redSchedule2_190(void)

{
  R_RED_NEXT(&redSchedule2_195,195)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redSchedule2 Releasetime 195
==========================================================*/
extern void redSchedule2_0(void);
void redSchedule2_195(void)

{
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 0
==========================================================*/
extern void redScheduleStart_5(void);
void redScheduleStart_0(void)

{
  bsLogPut(19,R_LOG_EVENT_1);
  R_RED_NEXT(&redScheduleStart_5,5)
  blueActivate(&blueKernel);
  redStartInternal(10);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 5
==========================================================*/
extern void redScheduleStart_0(void);
void redScheduleStart_5(void)

{
  blueActivate(&blueKernel);
}

/*==========================================================
** Blue thread xhpHandlerRxInternal()
==========================================================*/
extern blueThreadCB_t xhpHandlerRxCB;
void xhpHandlerRxInternal(void)

{ R_TYPE_TIME_EXEC execTime;

  bsLogPut(6,R_LOG_EVENT_1);
  R_EXEC_TIME_START(execTime)
  xhpHandlerRx_entry();
  R_EXEC_TIME_STOP(execTime,execTime,0u)
  bsLogPut(6,R_LOG_EVENT_2);
}

/*==========================================================
** Blue thread xhpHandlerTxInternal()
==========================================================*/
extern blueThreadCB_t xhpHandlerTxCB;
void xhpHandlerTxInternal(void)

{ R_TYPE_TIME_EXEC execTime;

  bsLogPut(7,R_LOG_EVENT_1);
  R_EXEC_TIME_START(execTime)
  xhpHandlerTx_entry();
  R_EXEC_TIME_STOP(execTime,execTime,0u)
  bsLogPut(7,R_LOG_EVENT_2);
}

/*==========================================================
** Rubus OS Initialisation
==========================================================*/
int_t bsRubusInit(void)

{ int_t rcode;

  rcode = bsInit();
  if (rcode != R_OK) {
    return(rcode);
  }

  rcode = redInit(&redScheduleStart);
  if (rcode != R_OK) {
    return(rcode);
  }

  rcode = greenInit();
  if (rcode != R_OK) {
    return(rcode);
  }

  rcode = blueInit();
  if (rcode != R_OK) {
    return(rcode);
  }

  rcode = blueThreadInitAll();
  if (rcode != R_OK) {
    return(rcode);
  }

  return(R_OK);
}

