#ifndef _R_EX_R_H_
#define _R_EX_R_H_
/*
** File: C:\Documents and Settings\emeliehe\Desktop\Embedded7\r_ex_r.h
** Generated by XMLLauncher v3.9.1.77 x86 2011a
**
** Copyright 1995-2011 Arcticus Systems AB, All rights reserved.
** The format and content in the File is protected by copyright.
** The File is furnished under a licence and may only be used in
** accordance with the terms of this licence.
** Rubus® is a registered trademark to which Arcticus has all exclusive rights.
*/

/*==========================================================
** Include files
==========================================================*/
#include <basic/bs_basic.h>
#include <red/r_thread.h>

#ifdef __cplusplus
extern "C" {
#endif

/*==========================================================
** Red Thread redStart
==========================================================*/
extern redThreadAttr_t const redStart;
extern void redStartMain(void);

/*==========================================================
** Red Thread blinky0
==========================================================*/
extern redThreadAttr_t const blinky0;
extern int blinky0Args;
extern void blinky0Main(int *args);

/*==========================================================
** Red Schedule redScheduleBlinky0
==========================================================*/
extern redSchedAttr_t const redScheduleBlinky0;

/*==========================================================
** Red Schedule redScheduleStart
==========================================================*/
extern redSchedAttr_t const redScheduleStart;


#ifdef __cplusplus
}
#endif


#endif
