#ifndef _R_EX_B_H_
#define _R_EX_B_H_
/*
** File: C:\Documents and Settings\emeliehe\Desktop\ESlab7\Embedded7\r_ex_b.h
** Generated by XMLLauncher v3.9.1.77 x86 2011a
**
** Copyright 1995-2011 Arcticus Systems AB, All rights reserved.
** The format and content in the File is protected by copyright.
** The File is furnished under a licence and may only be used in
** accordance with the terms of this licence.
** Rubus® is a registered trademark to which Arcticus has all exclusive rights.
*/

/*==========================================================
** Include files
==========================================================*/
#include <basic/bs_basic.h>
#include <blue/b_thread.h>
#include <blue/b_signal.h>

#ifdef __cplusplus
extern "C" {
#endif

/*==========================================================
** Blue Thread blueKernel
==========================================================*/
extern blueThreadAttr_t const blueKernel;
extern void blueKernelEntry(void);

/*==========================================================
** Blue Thread blueIdle
==========================================================*/
extern blueThreadAttr_t const blueIdle;
extern void rubusIdleMain(void);


#ifdef __cplusplus
}
#endif


#endif
